# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psicrom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_psicrom(object):
    def setupUi(self, psicrom):
        psicrom.setObjectName("psicrom")
        psicrom.resize(310, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(psicrom.sizePolicy().hasHeightForWidth())
        psicrom.setSizePolicy(sizePolicy)
        psicrom.setMinimumSize(QtCore.QSize(310, 350))
        psicrom.setMaximumSize(QtCore.QSize(310, 350))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        psicrom.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("psicrom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        psicrom.setWindowIcon(icon)
        psicrom.setWhatsThis("")
        psicrom.setAutoFillBackground(False)
        psicrom.setStyleSheet("QDialog{\n"
"    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"}")
        self.pushButton = QtWidgets.QPushButton(psicrom)
        self.pushButton.setGeometry(QtCore.QRect(210, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setToolTip("")
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(67, 149, 239);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    background-color:  rgb(0, 110, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius: 13.2px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(psicrom)
        self.label.setGeometry(QtCore.QRect(30, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label.setObjectName("label")
        self.temp_seca = QtWidgets.QLineEdit(psicrom)
        self.temp_seca.setGeometry(QtCore.QRect(30, 90, 51, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.temp_seca.setFont(font)
        self.temp_seca.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    padding-left: 10px;\n"
"    background-color:  rgb(37, 36, 44);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color:  rgb(43, 45, 56);\n"
"}")
        self.temp_seca.setText("")
        self.temp_seca.setObjectName("temp_seca")
        self.label_2 = QtWidgets.QLabel(psicrom)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 21, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(psicrom)
        self.label_3.setGeometry(QtCore.QRect(180, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_3.setObjectName("label_3")
        self.pto_rocio = QtWidgets.QLineEdit(psicrom)
        self.pto_rocio.setGeometry(QtCore.QRect(180, 90, 51, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.pto_rocio.setFont(font)
        self.pto_rocio.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    padding-left: 10px;\n"
"    background-color:  rgb(34, 36, 44);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color:  rgb(43, 45, 56);\n"
"}")
        self.pto_rocio.setText("")
        self.pto_rocio.setDragEnabled(False)
        self.pto_rocio.setObjectName("pto_rocio")
        self.hum = QtWidgets.QLabel(psicrom)
        self.hum.setGeometry(QtCore.QRect(10, 130, 151, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.hum.setFont(font)
        self.hum.setToolTip("")
        self.hum.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.hum.setText("")
        self.hum.setObjectName("hum")
        self.label_4 = QtWidgets.QLabel(psicrom)
        self.label_4.setGeometry(QtCore.QRect(240, 90, 21, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(psicrom)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 111, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(psicrom)
        self.label_6.setGeometry(QtCore.QRect(240, 250, 51, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(psicrom)
        self.label_7.setGeometry(QtCore.QRect(90, 250, 21, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(psicrom)
        self.label_8.setGeometry(QtCore.QRect(180, 210, 111, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(psicrom)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(67, 149, 239);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    background-color:  rgb(0, 110, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius: 13.2px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.temp_normal = QtWidgets.QLineEdit(psicrom)
        self.temp_normal.setGeometry(QtCore.QRect(30, 250, 51, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.temp_normal.setFont(font)
        self.temp_normal.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    padding-left: 10px;\n"
"    background-color:  rgb(37, 36, 44);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color:  rgb(43, 45, 56);\n"
"}")
        self.temp_normal.setText("")
        self.temp_normal.setObjectName("temp_normal")
        self.wind_speed = QtWidgets.QLineEdit(psicrom)
        self.wind_speed.setGeometry(QtCore.QRect(180, 250, 51, 31))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.wind_speed.setFont(font)
        self.wind_speed.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 13.2px;\n"
"    color: #FFF;\n"
"    padding-left: 10px;\n"
"    background-color:  rgb(34, 36, 44);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color:  rgb(43, 45, 56);\n"
"}")
        self.wind_speed.setText("")
        self.wind_speed.setDragEnabled(False)
        self.wind_speed.setObjectName("wind_speed")
        self.sterm = QtWidgets.QLabel(psicrom)
        self.sterm.setGeometry(QtCore.QRect(10, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.sterm.setFont(font)
        self.sterm.setToolTip("")
        self.sterm.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.sterm.setText("")
        self.sterm.setObjectName("sterm")
        self.label_9 = QtWidgets.QLabel(psicrom)
        self.label_9.setGeometry(QtCore.QRect(90, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(psicrom)
        self.label_10.setGeometry(QtCore.QRect(90, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("BasicCommercialLTW04-Light")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("    color: #FFF;\n"
"    background-color:  rgb(30, 32, 37);\n"
"")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(psicrom)
        QtCore.QMetaObject.connectSlotsByName(psicrom)
        psicrom.setTabOrder(self.pushButton, self.temp_seca)
        psicrom.setTabOrder(self.temp_seca, self.pto_rocio)

    def retranslateUi(self, psicrom):
        _translate = QtCore.QCoreApplication.translate
        psicrom.setWindowTitle(_translate("psicrom", "PSYcrom"))
        self.pushButton.setText(_translate("psicrom", "Calcular"))
        self.label.setText(_translate("psicrom", "Temp. seca"))
        self.temp_seca.setToolTip(_translate("psicrom", "<html><head/><body><p>Inserte la temperatura seca</p></body></html>"))
        self.label_2.setText(_translate("psicrom", "<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_3.setText(_translate("psicrom", "Punto rocio"))
        self.pto_rocio.setToolTip(_translate("psicrom", "<html><head/><body><p>Inserte el punto de rocio</p></body></html>"))
        self.label_4.setText(_translate("psicrom", "<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_5.setText(_translate("psicrom", "Temperatura"))
        self.label_6.setText(_translate("psicrom", "<html><head/><body><p>m/s</p></body></html>"))
        self.label_7.setText(_translate("psicrom", "<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_8.setText(_translate("psicrom", "Veloc. Viento"))
        self.pushButton_2.setText(_translate("psicrom", "Calcular"))
        self.temp_normal.setToolTip(_translate("psicrom", "<html><head/><body><p>Inserte la temperatura</p></body></html>"))
        self.wind_speed.setToolTip(_translate("psicrom", "<html><head/><body><p>Inserte la velocidad del viento</p></body></html>"))
        self.label_9.setText(_translate("psicrom", "Humedad Relativa"))
        self.label_10.setText(_translate("psicrom", "<html><head/><body><p>Sensación Térmica</p></body></html>"))
